// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyiydyyyylnrhphjxqul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5aXlkeXl5eWxucmhwaGp4cXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTY1MTAsImV4cCI6MjA2MTMzMjUxMH0.6MIlij_Y695eXJHzVKlrBxVwoFaC82272fGurm6WSe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);